---
# File: roles/dataloggers/tasks/main.yml
#
# Brief: This role manages dac_iot service account
#
# Author: Patrick Paul
#
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2017, Sa Majeste la Reine du Chef du Canada /
# Copyright 2017, Her Majesty in Right of Canada

- include: sysadmin.yml
  tags:
    - sysadmin
  become: true

- include: user.yml
  tags:
    - user

